pool:
  vmImage: 'Ubuntu-16.04'
variables:
  mtaBuilderImage: 'mta-archive-builder'
steps:
- task: DockerInstaller@0
  displayName: Install Docker
  inputs:
    dockerVersion: '17.09.0-ce'
- task: CmdLine@2
  displayName: Pull mta archive builder image
  inputs:
    script: 'docker pull ppiper/mta-archive-builder'
- task: CmdLine@2
  displayName: Display present working directory
  inputs:
    script: 'pwd'
#- task: Npm@1
#  inputs:
#    command: 'install'
#- task: Npm@1
#  inputs:
#    command: 'custom'
#    customCommand: 'run build'